spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nhahangne555@gmail.com
    password: vhwoffeyqhxketit
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  kafka:
#    bootstrap-servers: ${KAFKA_HOST:localhost}:9094
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: notification-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring:
#          deserializer:
#            value:
#              delegate:
#                class: org.springframework.kafka.support.serializer.JsonDeserializer
#          json:
#            trusted:
#              packages: "*"

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html

jwt:
  secret: laptrinhandroid/nhahang555/63ktpm1/daihocthuyloi/2024
  expiration: 3600000